In [36]:
import pandas as pd 
import numpy as np

df = pd.read_csv('../data/final_df.csv')
df.drop('workclass', axis=1, inplace=True)
df

ID            NAME_EDUCATION_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      5008804               Higher education           M            Y   
1      5008805               Higher education           M            Y   
2      5008806  Secondary / secondary special           M            Y   
3      5008808  Secondary / secondary special           F            N   
4      5008809  Secondary / secondary special           F            N   
...        ...                            ...         ...          ...   
36452  5149828  Secondary / secondary special           M            Y   
36453  5149834               Higher education           F            N   
36454  5149838               Higher education           F            N   
36455  5150049  Secondary / secondary special           F            N   
36456  5150337  Secondary / secondary special           M            N   

      FLAG_OWN_REALTY  AMT_INCOME_TOTAL      NAME_INCOME_TYPE  \
0                   Y         427500.00               Working   
1                   Y         427500.00               Working   
2                   Y         112500.00               Working   
3                   Y         270000.00  Commercial associate   
4                   Y         270000.00  Commercial associate   
...               ...               ...                   ...   
36452               Y         315000.00               Working   
36453               Y         157500.00  Commercial associate   
36454               Y         157500.00             Pensioner   
36455               Y         283500.00               Working   
36456               Y         112500.00               Working   

         NAME_FAMILY_STATUS  DAYS_EMPLOYED   age    occupation  capital  \
0            Civil marriage          -4542 36.33  Adm-clerical   509.39   
1            Civil marriage          -4542 36.33  Adm-clerical   509.39   
2                   Married          -1134 38.14  Craft-repair   440.54   
3      Single / not married          -3051 38.14  Craft-repair   440.54   
4      Single / not married          -3051 38.14  Craft-repair   440.54   
...                     ...            ...   ...           ...      ...   
36452               Married          -2420 38.14  Craft-repair   440.54   
36453               Married          -1325 36.33  Adm-clerical   509.39   
36454               Married          -1325 36.33  Adm-clerical   509.39   
36455               Married           -655 38.14  Craft-repair   440.54   
36456  Single / not married          -1193 38.14  Craft-repair   440.54   

       hours-per-week  credit_decision  
0               39.45                1  
1               39.45                1  
2               39.55               -1  
3               39.55               -1  
4               39.55                0  
...               ...              ...  
36452           39.55               -1  
36453           39.45               -1  
36454           39.45               -1  
36455           39.55               -1  
36456           39.55               -1  

[36457 rows x 14 columns]

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36457 entries, 0 to 36456
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   36457 non-null  int64  
 1   NAME_EDUCATION_TYPE  36457 non-null  object 
 2   CODE_GENDER          36457 non-null  object 
 3   FLAG_OWN_CAR         36457 non-null  object 
 4   FLAG_OWN_REALTY      36457 non-null  object 
 5   AMT_INCOME_TOTAL     36457 non-null  float64
 6   NAME_INCOME_TYPE     36457 non-null  object 
 7   NAME_FAMILY_STATUS   36457 non-null  object 
 8   DAYS_EMPLOYED        36457 non-null  int64  
 9   age                  36457 non-null  float64
 10  occupation           36457 non-null  object 
 11  capital              36457 non-null  float64
 12  hours-per-week       36457 non-null  float64
 13  credit_decision      36457 non-null  int64  
dtypes: float64(4), int64(3), object(7)
memory usage: 3.9+ MB


In [38]:
for col in df.columns:
    if df[col].dtype == 'object':
        print(col,': ',df[col].unique())

NAME_EDUCATION_TYPE :  ['Higher education' 'Secondary / secondary special' 'Lower secondary'
 'Academic degree']
CODE_GENDER :  ['M' 'F']
FLAG_OWN_CAR :  ['Y' 'N']
FLAG_OWN_REALTY :  ['Y' 'N']
NAME_INCOME_TYPE :  ['Working' 'Commercial associate' 'Pensioner' 'State servant' 'Student']
NAME_FAMILY_STATUS :  ['Civil marriage' 'Married' 'Single / not married' 'Separated' 'Widow']
occupation :  ['Adm-clerical' 'Craft-repair' 'Other-service' 'Prof-specialty']


In [39]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
y = df['credit_decision']
df.drop(['credit_decision','ID'],axis=1,inplace=True)
for col in df.columns:
    if df[col].dtype != 'object':
        df[col] = scaler.fit_transform(df[[col]])
    else:
        df_dummy = pd.get_dummies(df[col],drop_first=True,prefix=col).astype(int)
        df = pd.concat([df,df_dummy],axis=1)
        df.drop(col,axis=1,inplace=True)
df

AMT_INCOME_TOTAL  DAYS_EMPLOYED   age  capital  hours-per-week  \
0                  2.37          -0.46 -1.13     0.67           -0.46   
1                  2.37          -0.46 -1.13     0.67           -0.46   
2                 -0.73          -0.44  0.32    -0.24            0.22   
3                  0.82          -0.45  0.32    -0.24            0.22   
4                  0.82          -0.45  0.32    -0.24            0.22   
...                 ...            ...   ...      ...             ...   
36452              1.26          -0.45  0.32    -0.24            0.22   
36453             -0.29          -0.44 -1.13     0.67           -0.46   
36454             -0.29          -0.44 -1.13     0.67           -0.46   
36455              0.95          -0.44  0.32    -0.24            0.22   
36456             -0.73          -0.44  0.32    -0.24            0.22   

       NAME_EDUCATION_TYPE_Higher education  \
0                                         1   
1                                         1   
2                                         0   
3                                         0   
4                                         0   
...                                     ...   
36452                                     0   
36453                                     1   
36454                                     1   
36455                                     0   
36456                                     0   

       NAME_EDUCATION_TYPE_Lower secondary  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   
...                                    ...   
36452                                    0   
36453                                    0   
36454                                    0   
36455                                    0   
36456                                    0   

       NAME_EDUCATION_TYPE_Secondary / secondary special  CODE_GENDER_M  \
0                                                      0              1   
1                                                      0              1   
2                                                      1              1   
3                                                      1              0   
4                                                      1              0   
...                                                  ...            ...   
36452                                                  1              1   
36453                                                  0              0   
36454                                                  0              0   
36455                                                  1              0   
36456                                                  1              1   

       FLAG_OWN_CAR_Y  ...  NAME_INCOME_TYPE_State servant  \
0                   1  ...                               0   
1                   1  ...                               0   
2                   1  ...                               0   
3                   0  ...                               0   
4                   0  ...                               0   
...               ...  ...                             ...   
36452               1  ...                               0   
36453               0  ...                               0   
36454               0  ...                               0   
36455               0  ...                               0   
36456               0  ...                               0   

       NAME_INCOME_TYPE_Student  NAME_INCOME_TYPE_Working  \
0                             0                         1   
1                             0                         1   
2                             0                         1   
3                             0                         0   
4                             0                         0   


In [40]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

df_non_education = df.loc[:, ~df.columns.str.startswith('NAME_EDUCATION_TYPE')]
vif_data = pd.DataFrame()
vif_data["feature"] = df_non_education.columns
vif_data["VIF"] = [variance_inflation_factor(df_non_education.values, i)
                          for i in range(len(df_non_education.columns))]
vif_data.sort_values(by="VIF", ascending=False)

d:\Python3.9\lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)


feature    VIF
18                occupation_Prof-specialty    inf
2                                       age    inf
3                                   capital    inf
4                            hours-per-week    inf
17                 occupation_Other-service    inf
16                  occupation_Craft-repair    inf
1                             DAYS_EMPLOYED 281.87
8                NAME_INCOME_TYPE_Pensioner 281.66
12               NAME_FAMILY_STATUS_Married   3.00
14  NAME_FAMILY_STATUS_Single / not married   2.30
13             NAME_FAMILY_STATUS_Separated   1.62
11                 NAME_INCOME_TYPE_Working   1.61
15                 NAME_FAMILY_STATUS_Widow   1.52
9            NAME_INCOME_TYPE_State servant   1.25
5                             CODE_GENDER_M   1.22
6                            FLAG_OWN_CAR_Y   1.21
0                          AMT_INCOME_TOTAL   1.16
7                         FLAG_OWN_REALTY_Y   1.01
10                 NAME_INCOME_TYPE_Student   1.00

In [41]:
# Colinearity check
pd.set_option('display.float_format', '{:.2f}'.format)
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.DataFrame()
vif_data["feature"] = df.columns
vif_data["VIF"] = [variance_inflation_factor(df.values, i)
                          for i in range(len(df.columns))]
vif_data.sort_values(by="VIF", ascending=False)

d:\Python3.9\lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)


feature          VIF
2                                                 age          inf
3                                             capital          inf
4                                      hours-per-week          inf
5                NAME_EDUCATION_TYPE_Higher education          inf
20                           occupation_Other-service 290872541.31
6                 NAME_EDUCATION_TYPE_Lower secondary 173628402.20
21                          occupation_Prof-specialty   1474956.66
7   NAME_EDUCATION_TYPE_Secondary / secondary special    132681.28
19                            occupation_Craft-repair     79443.58
1                                       DAYS_EMPLOYED       281.86
11                         NAME_INCOME_TYPE_Pensioner       281.66
15                         NAME_FAMILY_STATUS_Married         3.00
17            NAME_FAMILY_STATUS_Single / not married         2.30
16                       NAME_FAMILY_STATUS_Separated         1.62
14                           NAME_INCOME_TYPE_Working         1.61
18                           NAME_FAMILY_STATUS_Widow         1.52
12                     NAME_INCOME_TYPE_State servant         1.25
8                                       CODE_GENDER_M         1.22
9                                      FLAG_OWN_CAR_Y         1.21
0                                    AMT_INCOME_TOTAL         1.16
10                                  FLAG_OWN_REALTY_Y         1.01
13                           NAME_INCOME_TYPE_Student         1.00

In [42]:
drop_columns = vif_data['feature'][vif_data['VIF'] > 5].tolist()
print(drop_columns)
X = df.drop(drop_columns,axis=1)
X

['DAYS_EMPLOYED', 'age', 'capital', 'hours-per-week', 'NAME_EDUCATION_TYPE_Higher education', 'NAME_EDUCATION_TYPE_Lower secondary', 'NAME_EDUCATION_TYPE_Secondary / secondary special', 'NAME_INCOME_TYPE_Pensioner', 'occupation_Craft-repair', 'occupation_Other-service', 'occupation_Prof-specialty']


AMT_INCOME_TOTAL  CODE_GENDER_M  FLAG_OWN_CAR_Y  FLAG_OWN_REALTY_Y  \
0                  2.37              1               1                  1   
1                  2.37              1               1                  1   
2                 -0.73              1               1                  1   
3                  0.82              0               0                  1   
4                  0.82              0               0                  1   
...                 ...            ...             ...                ...   
36452              1.26              1               1                  1   
36453             -0.29              0               0                  1   
36454             -0.29              0               0                  1   
36455              0.95              0               0                  1   
36456             -0.73              1               0                  1   

       NAME_INCOME_TYPE_State servant  NAME_INCOME_TYPE_Student  \
0                                   0                         0   
1                                   0                         0   
2                                   0                         0   
3                                   0                         0   
4                                   0                         0   
...                               ...                       ...   
36452                               0                         0   
36453                               0                         0   
36454                               0                         0   
36455                               0                         0   
36456                               0                         0   

       NAME_INCOME_TYPE_Working  NAME_FAMILY_STATUS_Married  \
0                             1                           0   
1                             1                           0   
2                             1                           1   
3                             0                           0   
4                             0                           0   
...                         ...                         ...   
36452                         1                           1   
36453                         0                           1   
36454                         0                           1   
36455                         1                           1   
36456                         1                           0   

       NAME_FAMILY_STATUS_Separated  NAME_FAMILY_STATUS_Single / not married  \
0                                 0                                        0   
1                                 0                                        0   
2                                 0                                        0   
3                                 0                                        1   
4                                 0                                        1   
...                             ...                                      ...   
36452                             0                                        0   
36453                             0                                        0   
36454                             0                                        0   
36455                             0                                        0   
36456                             0                                        1   

       NAME_FAMILY_STATUS_Widow  
0                             0  
1                             0  
2                             0  
3                             0  
4                             0  
...                         ...  
36452                         0  
36453                         0  
36454                         0  
36455                         0  
36456                         0  

[36457 rows x 11 columns]

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_test.value_counts()
model = LogisticRegression(multi_class='multinomial',solver='lbfgs',max_iter=1000)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
# y.value_counts()

              precision    recall  f1-score   support

          -1       0.65      1.00      0.79      4761
           0       0.00      0.00      0.00       687
           1       0.75      0.00      0.00      1844

    accuracy                           0.65      7292
   macro avg       0.47      0.33      0.26      7292
weighted avg       0.62      0.65      0.52      7292

[[4760    0    1]
 [ 687    0    0]
 [1841    0    3]]


d:\Python3.9\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python3.9\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python3.9\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [45]:
model.coef_

array([[ 3.90956456e-04,  3.38654906e-03, -5.10702965e-02,
         3.11805077e-02,  3.43890151e-02, -5.09100705e-01,
         4.77680202e-03,  4.64091506e-02,  7.34650175e-02,
         6.61133253e-02,  6.01544777e-02],
       [ 5.93985683e-02, -7.95776661e-04,  4.38694154e-02,
        -3.89442744e-02, -8.30747418e-02, -3.76272111e-01,
         4.80819455e-03, -7.41137177e-02, -6.30697891e-02,
        -1.56541637e-01, -9.72791766e-03],
       [-5.97895248e-02, -2.59077240e-03,  7.20088110e-03,
         7.76376664e-03,  4.86857266e-02,  8.85372816e-01,
        -9.58499657e-03,  2.77045671e-02, -1.03952284e-02,
         9.04283115e-02, -5.04265600e-02]])