In [79]:
import pandas as pd 
app_record = pd.read_csv('../data/application_record.csv')
final_decision = pd.read_csv('../data/credit_decision.csv')
app_record_init = pd.merge(app_record, final_decision, on='ID', how='inner')
app_record_init

ID CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  \
0      5008804           M            Y               Y             0   
1      5008805           M            Y               Y             0   
2      5008806           M            Y               Y             0   
3      5008808           F            N               Y             0   
4      5008809           F            N               Y             0   
...        ...         ...          ...             ...           ...   
36452  5149828           M            Y               Y             0   
36453  5149834           F            N               Y             0   
36454  5149838           F            N               Y             0   
36455  5150049           F            N               Y             0   
36456  5150337           M            N               Y             0   

       AMT_INCOME_TOTAL      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE  \
0              427500.0               Working               Higher education   
1              427500.0               Working               Higher education   
2              112500.0               Working  Secondary / secondary special   
3              270000.0  Commercial associate  Secondary / secondary special   
4              270000.0  Commercial associate  Secondary / secondary special   
...                 ...                   ...                            ...   
36452          315000.0               Working  Secondary / secondary special   
36453          157500.0  Commercial associate               Higher education   
36454          157500.0             Pensioner               Higher education   
36455          283500.0               Working  Secondary / secondary special   
36456          112500.0               Working  Secondary / secondary special   

         NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0            Civil marriage   Rented apartment      -12005          -4542   
1            Civil marriage   Rented apartment      -12005          -4542   
2                   Married  House / apartment      -21474          -1134   
3      Single / not married  House / apartment      -19110          -3051   
4      Single / not married  House / apartment      -19110          -3051   
...                     ...                ...         ...            ...   
36452               Married  House / apartment      -17348          -2420   
36453               Married  House / apartment      -12387          -1325   
36454               Married  House / apartment      -12387          -1325   
36455               Married  House / apartment      -17958           -655   
36456  Single / not married   Rented apartment       -9188          -1193   

       FLAG_MOBIL  FLAG_WORK_PHONE  FLAG_PHONE  FLAG_EMAIL OCCUPATION_TYPE  \
0               1                1           0           0             NaN   
1               1                1           0           0             NaN   
2               1                0           0           0  Security staff   
3               1                0           1           1     Sales staff   
4               1                0           1           1     Sales staff   
...           ...              ...         ...         ...             ...   
36452           1                0           0           0        Managers   
36453           1                0           1           1  Medicine staff   
36454           1                0           1           1  Medicine staff   
36455           1                0           0           0     Sales staff   
36456           1                0           0           0        Laborers   

       CNT_FAM_MEMBERS  credit_decision  
0                  2.0                1  
1                  2.0                1  
2                  2.0               -1  
3                  1.0               -1  
4                  1.0                0  
...                ...              ...  
36452             

In [80]:
income_train = pd.read_csv('../data/income_train.csv')
income_test = pd.read_csv('../data/income_test.csv')
income = pd.concat([income_train, income_test])
income.drop('income_>50K', axis=1, inplace=True)

def education_categorize(x):
    if x['education'] in ['9th','10th','11th','12th','HS-grad']:
        return 'Secondary / secondary special'
    elif x['education'] in ['1st-4th','5th-6th','7th-8th','Preschool']:
        return 'Lower secondary'
    elif x['education'] in ['Assoc-acdm','Assoc-voc','Some-college']:
        return 'Higher education'
    else:
        return 'Academic degree'
income['education'] = income.apply(education_categorize, axis=1)

display(income.info())
display(income.head())


<class 'pandas.core.frame.DataFrame'>
Index: 44856 entries, 0 to 898
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              44856 non-null  int64 
 1   workclass        42358 non-null  object
 2   fnlwgt           44856 non-null  int64 
 3   education        44856 non-null  object
 4   educational-num  44856 non-null  int64 
 5   marital-status   44856 non-null  object
 6   occupation       42350 non-null  object
 7   relationship     44856 non-null  object
 8   race             44856 non-null  object
 9   gender           44856 non-null  object
 10  capital-gain     44856 non-null  int64 
 11  capital-loss     44856 non-null  int64 
 12  hours-per-week   44856 non-null  int64 
 13  native-country   44093 non-null  object
dtypes: int64(6), object(8)
memory usage: 5.1+ MB


None

age  workclass  fnlwgt                      education  educational-num  \
0   67    Private  366425                Academic degree               16   
1   17    Private  244602  Secondary / secondary special                8   
2   31    Private  174201                Academic degree               13   
3   58  State-gov  110199                Lower secondary                4   
4   25  State-gov  149248               Higher education               10   

       marital-status        occupation   relationship   race gender  \
0            Divorced   Exec-managerial  Not-in-family  White   Male   
1       Never-married     Other-service      Own-child  White   Male   
2  Married-civ-spouse   Exec-managerial        Husband  White   Male   
3  Married-civ-spouse  Transport-moving        Husband  White   Male   
4       Never-married     Other-service  Not-in-family  Black   Male   

   capital-gain  capital-loss  hours-per-week native-country  
0         99999             0              60  United-States  
1             0             0              15  United-States  
2             0             0              40  United-States  
3             0             0              40  United-States  
4             0             0              40  United-States

In [81]:
income_try = income.groupby('education')

jobs = pd.DataFrame()
for i in income_try:
    print(i[0])
    jobs = pd.concat([jobs, i[1]["occupation"].value_counts()[:6]])
    # display(i[1]["occupation"].value_counts()[:6])
    print("------------------------------------")
    
jobs.index.value_counts()

Academic degree
------------------------------------
Higher education
------------------------------------
Lower secondary
------------------------------------
Secondary / secondary special
------------------------------------


Craft-repair         4
Sales                3
Adm-clerical         3
Other-service        3
Prof-specialty       2
Exec-managerial      2
Machine-op-inspct    2
Transport-moving     2
Tech-support         1
Farming-fishing      1
Handlers-cleaners    1
Name: count, dtype: int64

Craft-repair         4
Sales                3
Adm-clerical         3
Other-service        3

In [82]:
prob = []
for i in income_try:
    prob.append(i[1]["occupation"].value_counts().loc[["Craft-repair", "Sales", "Adm-clerical", "Other-service"], ].values)

job = ["Craft-repair", "Sales", "Adm-clerical", "Other-service"]
prob


[array([ 341, 1398,  809,  282], dtype=int64),
 array([1670, 1724, 2187, 1315], dtype=int64),
 array([252,  64,  34, 291], dtype=int64),
 array([3382, 1886, 2102, 2646], dtype=int64)]

In [83]:
import numpy as np
def income_agg(x):
    if x.dtypes == np.int64:
        return x.mean()
    elif x.dtypes == object:
        return x.mode()[0]
    
income = income.groupby('education').agg(income_agg).reset_index()

income

education        age workclass         fnlwgt  \
0                Academic degree  40.906770   Private  186427.490515   
1               Higher education  36.332433   Private  188749.516427   
2                Lower secondary  47.083535   Private  209247.739709   
3  Secondary / secondary special  38.135474   Private  190745.016961   

   educational-num      marital-status      occupation relationship   race  \
0        13.504990  Married-civ-spouse  Prof-specialty      Husband  White   
1        10.361836  Married-civ-spouse    Adm-clerical      Husband  White   
2         3.298426  Married-civ-spouse   Other-service      Husband  White   
3         8.436503  Married-civ-spouse    Craft-repair      Husband  White   

  gender  capital-gain  capital-loss  hours-per-week native-country  
0   Male   2783.699811    148.066799       43.297761  United-States  
1   Male    586.416742     77.025953       39.454320  United-States  
2   Male    290.303874     61.390436       38.736077  United-States  
3   Male    504.779882     64.238199       39.552563  United-States

In [84]:
income['capital'] = income['capital-gain'] - income['capital-loss']
income

education        age workclass         fnlwgt  \
0                Academic degree  40.906770   Private  186427.490515   
1               Higher education  36.332433   Private  188749.516427   
2                Lower secondary  47.083535   Private  209247.739709   
3  Secondary / secondary special  38.135474   Private  190745.016961   

   educational-num      marital-status      occupation relationship   race  \
0        13.504990  Married-civ-spouse  Prof-specialty      Husband  White   
1        10.361836  Married-civ-spouse    Adm-clerical      Husband  White   
2         3.298426  Married-civ-spouse   Other-service      Husband  White   
3         8.436503  Married-civ-spouse    Craft-repair      Husband  White   

  gender  capital-gain  capital-loss  hours-per-week native-country  \
0   Male   2783.699811    148.066799       43.297761  United-States   
1   Male    586.416742     77.025953       39.454320  United-States   
2   Male    290.303874     61.390436       38.736077  United-States   
3   Male    504.779882     64.238199       39.552563  United-States   

       capital  
0  2635.633013  
1   509.390789  
2   228.913438  
3   440.541682

In [88]:
app_record_init['NAME_EDUCATION_TYPE'] = app_record_init.apply(lambda x: 'Secondary / secondary special'
                                                    if x['NAME_EDUCATION_TYPE'] in ['Secondary / secondary special', 'Incomplete higher'] 
                                                    else x['NAME_EDUCATION_TYPE'], axis=1)

app_record = app_record_init[['ID','NAME_EDUCATION_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 
                                   'NAME_FAMILY_STATUS', 'DAYS_EMPLOYED']]

result_df = pd.merge(app_record, income[['education','age', 'workclass', 'occupation', 'capital', 'hours-per-week']], 
                     left_on='NAME_EDUCATION_TYPE', right_on='education', how='left')

result_df["credit_decision"] = app_record_init["credit_decision"]

result_df.drop('education', axis=1, inplace=True)
result_df.info()
result_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36457 entries, 0 to 36456
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   36457 non-null  int64  
 1   NAME_EDUCATION_TYPE  36457 non-null  object 
 2   CODE_GENDER          36457 non-null  object 
 3   FLAG_OWN_CAR         36457 non-null  object 
 4   FLAG_OWN_REALTY      36457 non-null  object 
 5   AMT_INCOME_TOTAL     36457 non-null  float64
 6   NAME_INCOME_TYPE     36457 non-null  object 
 7   NAME_FAMILY_STATUS   36457 non-null  object 
 8   DAYS_EMPLOYED        36457 non-null  int64  
 9   age                  36457 non-null  float64
 10  workclass            36457 non-null  object 
 11  occupation           36457 non-null  object 
 12  capital              36457 non-null  float64
 13  hours-per-week       36457 non-null  float64
 14  credit_decision      36457 non-null  int64  
dtypes: float64(4), int64(3), object(8)
m

ID            NAME_EDUCATION_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      5008804               Higher education           M            Y   
1      5008805               Higher education           M            Y   
2      5008806  Secondary / secondary special           M            Y   
3      5008808  Secondary / secondary special           F            N   
4      5008809  Secondary / secondary special           F            N   
...        ...                            ...         ...          ...   
36452  5149828  Secondary / secondary special           M            Y   
36453  5149834               Higher education           F            N   
36454  5149838               Higher education           F            N   
36455  5150049  Secondary / secondary special           F            N   
36456  5150337  Secondary / secondary special           M            N   

      FLAG_OWN_REALTY  AMT_INCOME_TOTAL      NAME_INCOME_TYPE  \
0                   Y          427500.0               Working   
1                   Y          427500.0               Working   
2                   Y          112500.0               Working   
3                   Y          270000.0  Commercial associate   
4                   Y          270000.0  Commercial associate   
...               ...               ...                   ...   
36452               Y          315000.0               Working   
36453               Y          157500.0  Commercial associate   
36454               Y          157500.0             Pensioner   
36455               Y          283500.0               Working   
36456               Y          112500.0               Working   

         NAME_FAMILY_STATUS  DAYS_EMPLOYED        age workclass    occupation  \
0            Civil marriage          -4542  36.332433   Private  Adm-clerical   
1            Civil marriage          -4542  36.332433   Private  Adm-clerical   
2                   Married          -1134  38.135474   Private  Craft-repair   
3      Single / not married          -3051  38.135474   Private  Craft-repair   
4      Single / not married          -3051  38.135474   Private  Craft-repair   
...                     ...            ...        ...       ...           ...   
36452               Married          -2420  38.135474   Private  Craft-repair   
36453               Married          -1325  36.332433   Private  Adm-clerical   
36454               Married          -1325  36.332433   Private  Adm-clerical   
36455               Married           -655  38.135474   Private  Craft-repair   
36456  Single / not married          -1193  38.135474   Private  Craft-repair   

          capital  hours-per-week  credit_decision  
0      509.390789       39.454320                1  
1      509.390789       39.454320                1  
2      440.541682       39.552563               -1  
3      440.541682       39.552563               -1  
4      440.541682       39.552563                0  
...           ...             ...              ...  
36452  440.541682       39.552563               -1  
36453  509.390789       39.454320               -1  
36454  509.390789       39.454320               -1  
36455  440.541682       39.552563               -1  
36456  440.541682       39.552563               -1  

[36457 rows x 15 columns]

In [91]:
display(job)
display(prob)
import random
def replace_job(x):
    if x['NAME_EDUCATION_TYPE'] == "Academic degree":
        samples = random.choices(job, k=1, weights = prob[0])
        return samples[0]

    elif x['NAME_EDUCATION_TYPE'] == "Higher education":
        samples = random.choices(job, k=1, weights = prob[1])
        return samples[0]

    elif x['NAME_EDUCATION_TYPE'] == "Lower secondary":
        samples = random.choices(job, k=1, weights = prob[2])
        return samples[0]

    else:
        samples = random.choices(job, k=1, weights = prob[3])
        return samples[0]

['Craft-repair', 'Sales', 'Adm-clerical', 'Other-service']

[array([ 341, 1398,  809,  282], dtype=int64),
 array([1670, 1724, 2187, 1315], dtype=int64),
 array([252,  64,  34, 291], dtype=int64),
 array([3382, 1886, 2102, 2646], dtype=int64)]

In [92]:
result_df['occupation'] = result_df.apply(replace_job, axis=1)

result_df

ID            NAME_EDUCATION_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      5008804               Higher education           M            Y   
1      5008805               Higher education           M            Y   
2      5008806  Secondary / secondary special           M            Y   
3      5008808  Secondary / secondary special           F            N   
4      5008809  Secondary / secondary special           F            N   
...        ...                            ...         ...          ...   
36452  5149828  Secondary / secondary special           M            Y   
36453  5149834               Higher education           F            N   
36454  5149838               Higher education           F            N   
36455  5150049  Secondary / secondary special           F            N   
36456  5150337  Secondary / secondary special           M            N   

      FLAG_OWN_REALTY  AMT_INCOME_TOTAL      NAME_INCOME_TYPE  \
0                   Y          427500.0               Working   
1                   Y          427500.0               Working   
2                   Y          112500.0               Working   
3                   Y          270000.0  Commercial associate   
4                   Y          270000.0  Commercial associate   
...               ...               ...                   ...   
36452               Y          315000.0               Working   
36453               Y          157500.0  Commercial associate   
36454               Y          157500.0             Pensioner   
36455               Y          283500.0               Working   
36456               Y          112500.0               Working   

         NAME_FAMILY_STATUS  DAYS_EMPLOYED        age workclass  \
0            Civil marriage          -4542  36.332433   Private   
1            Civil marriage          -4542  36.332433   Private   
2                   Married          -1134  38.135474   Private   
3      Single / not married          -3051  38.135474   Private   
4      Single / not married          -3051  38.135474   Private   
...                     ...            ...        ...       ...   
36452               Married          -2420  38.135474   Private   
36453               Married          -1325  36.332433   Private   
36454               Married          -1325  36.332433   Private   
36455               Married           -655  38.135474   Private   
36456  Single / not married          -1193  38.135474   Private   

          occupation     capital  hours-per-week  credit_decision  
0              Sales  509.390789       39.454320                1  
1              Sales  509.390789       39.454320                1  
2       Adm-clerical  440.541682       39.552563               -1  
3      Other-service  440.541682       39.552563               -1  
4       Craft-repair  440.541682       39.552563                0  
...              ...         ...             ...              ...  
36452   Craft-repair  440.541682       39.552563               -1  
36453  Other-service  509.390789       39.454320               -1  
36454   Adm-clerical  509.390789       39.454320               -1  
36455  Other-service  440.541682       39.552563               -1  
36456   Craft-repair  440.541682       39.552563               -1  

[36457 rows x 15 columns]

In [93]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
y = result_df['credit_decision']
result_df.drop(['credit_decision','ID'],axis=1,inplace=True)
for col in result_df.columns:
    if result_df[col].dtype != 'object':
        result_df[col] = scaler.fit_transform(result_df[[col]])
    else:
        df_dummy = pd.get_dummies(result_df[col],drop_first=True,prefix=col).astype(int)
        result_df = pd.concat([result_df,df_dummy],axis=1)
        result_df.drop(col,axis=1,inplace=True)
        
result_df

AMT_INCOME_TOTAL  DAYS_EMPLOYED       age   capital  hours-per-week  \
0              2.365845      -0.463532 -1.131061  0.672369       -0.462054   
1              2.365845      -0.463532 -1.131061  0.672369       -0.462054   
2             -0.728827      -0.438774  0.315873 -0.244936        0.219806   
3              0.818509      -0.452700  0.315873 -0.244936        0.219806   
4              0.818509      -0.452700  0.315873 -0.244936        0.219806   
...                 ...            ...       ...       ...             ...   
36452          1.260605      -0.448116  0.315873 -0.244936        0.219806   
36453         -0.286731      -0.440161 -1.131061  0.672369       -0.462054   
36454         -0.286731      -0.440161 -1.131061  0.672369       -0.462054   
36455          0.951138      -0.435294  0.315873 -0.244936        0.219806   
36456         -0.728827      -0.439202  0.315873 -0.244936        0.219806   

       NAME_EDUCATION_TYPE_Higher education  \
0                                         1   
1                                         1   
2                                         0   
3                                         0   
4                                         0   
...                                     ...   
36452                                     0   
36453                                     1   
36454                                     1   
36455                                     0   
36456                                     0   

       NAME_EDUCATION_TYPE_Lower secondary  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   
...                                    ...   
36452                                    0   
36453                                    0   
36454                                    0   
36455                                    0   
36456                                    0   

       NAME_EDUCATION_TYPE_Secondary / secondary special  CODE_GENDER_M  \
0                                                      0              1   
1                                                      0              1   
2                                                      1              1   
3                                                      1              0   
4                                                      1              0   
...                                                  ...            ...   
36452                                                  1              1   
36453                                                  0              0   
36454                                                  0              0   
36455                                                  1              0   
36456                                                  1              1   

       FLAG_OWN_CAR_Y  ...  NAME_INCOME_TYPE_State servant  \
0                   1  ...                               0   
1                   1  ...                               0   
2                   1  ...                               0   
3                   0  ...                               0   
4                   0  ...                               0   
...               ...  ...                             ...   
36452               1  ...                               0   
36453               0  ...                               0   
36454               0  ...                               0   
36455               0  ...                               0   
36456               0  ...                               0   

       NAME_INCOME_TYPE_Student  NAME_INCOME_TYPE_Working  \
0                             0                         1   
1                             0                         1   
2                             0                         1   
3                             0                         0   
4

In [94]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

df_non_education = result_df.loc[:, ~result_df.columns.str.startswith('NAME_EDUCATION_TYPE')]
vif_data = pd.DataFrame()
vif_data["feature"] = df_non_education.columns
vif_data["VIF"] = [variance_inflation_factor(df_non_education.values, i)
                          for i in range(len(df_non_education.columns))]
vif_data.sort_values(by="VIF", ascending=False)

feature        VIF
8                NAME_INCOME_TYPE_Pensioner  88.321805
1                             DAYS_EMPLOYED  77.223546
12               NAME_FAMILY_STATUS_Married   8.392651
11                 NAME_INCOME_TYPE_Working   3.234748
7                         FLAG_OWN_REALTY_Y   3.014366
3                                   capital   2.667881
14  NAME_FAMILY_STATUS_Single / not married   2.400129
16                  occupation_Craft-repair   2.271552
4                            hours-per-week   2.234966
17                 occupation_Other-service   2.012360
6                            FLAG_OWN_CAR_Y   1.946894
5                             CODE_GENDER_M   1.814653
18                         occupation_Sales   1.804060
13             NAME_FAMILY_STATUS_Separated   1.611398
15                 NAME_FAMILY_STATUS_Widow   1.506960
9            NAME_INCOME_TYPE_State servant   1.353561
2                                       age   1.333455
0                          AMT_INCOME_TOTAL   1.161927
10                 NAME_INCOME_TYPE_Student   1.002235

In [98]:
drop_columns = vif_data['feature'][vif_data['VIF'] > 5].tolist()
print(drop_columns)
X = result_df.drop(drop_columns,axis=1)
X

['DAYS_EMPLOYED', 'NAME_INCOME_TYPE_Pensioner', 'NAME_FAMILY_STATUS_Married']


AMT_INCOME_TOTAL       age   capital  hours-per-week  \
0              2.365845 -1.131061  0.672369       -0.462054   
1              2.365845 -1.131061  0.672369       -0.462054   
2             -0.728827  0.315873 -0.244936        0.219806   
3              0.818509  0.315873 -0.244936        0.219806   
4              0.818509  0.315873 -0.244936        0.219806   
...                 ...       ...       ...             ...   
36452          1.260605  0.315873 -0.244936        0.219806   
36453         -0.286731 -1.131061  0.672369       -0.462054   
36454         -0.286731 -1.131061  0.672369       -0.462054   
36455          0.951138  0.315873 -0.244936        0.219806   
36456         -0.728827  0.315873 -0.244936        0.219806   

       NAME_EDUCATION_TYPE_Higher education  \
0                                         1   
1                                         1   
2                                         0   
3                                         0   
4                                         0   
...                                     ...   
36452                                     0   
36453                                     1   
36454                                     1   
36455                                     0   
36456                                     0   

       NAME_EDUCATION_TYPE_Lower secondary  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   
...                                    ...   
36452                                    0   
36453                                    0   
36454                                    0   
36455                                    0   
36456                                    0   

       NAME_EDUCATION_TYPE_Secondary / secondary special  CODE_GENDER_M  \
0                                                      0              1   
1                                                      0              1   
2                                                      1              1   
3                                                      1              0   
4                                                      1              0   
...                                                  ...            ...   
36452                                                  1              1   
36453                                                  0              0   
36454                                                  0              0   
36455                                                  1              0   
36456                                                  1              1   

       FLAG_OWN_CAR_Y  FLAG_OWN_REALTY_Y  NAME_INCOME_TYPE_State servant  \
0                   1                  1                               0   
1                   1                  1                               0   
2                   1                  1                               0   
3                   0                  1                               0   
4                   0                  1                               0   
...               ...                ...                             ...   
36452               1                  1                               0   
36453               0                  1                               0   
36454               0                  1                               0   
36455               0                  1                               0   
36456               0                  1                               0   

       NAME_INCOME_TYPE_Student  NAME_INCOME_TYPE_Working  \
0                             0                         1   
1                             0                         1   
2                             0                         1   
3                             0                         0   
4            

In [99]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
X = result_df
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_test.value_counts()
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

          -1       0.65      1.00      0.79      4761
           0       0.00      0.00      0.00       687
           1       0.57      0.00      0.00      1844

    accuracy                           0.65      7292
   macro avg       0.41      0.33      0.26      7292
weighted avg       0.57      0.65      0.52      7292

[[4758    0    3]
 [ 687    0    0]
 [1840    0    4]]


d:\Python3.9\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python3.9\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python3.9\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [100]:
unique_values, counts = np.unique(y_pred, return_counts=True)
print("不同值及其出现次数:", dict(zip(unique_values, counts)))

不同值及其出现次数: {-1: 7285, 1: 7}
